# Generated by Django 2.2.1 on 2019-11-22 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tom_targets', '0015_auto_20190923_2233'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=[
            migrations.CreateModel(
                name='TargetListTargets',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tom_targets.Target')),
                ],
                options={
                    'db_table': 'tom_targets_targetlist_targets',
                },
            ),
            migrations.AlterField(
                model_name='targetlist',
                name='targets',
                field=models.ManyToManyField(through='tom_targets.TargetListTargets', to='tom_targets.Target'),
            ),
            migrations.AddField(
                model_name='targetlisttargets',
                name='targetlist',
                field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tom_targets.TargetList'),
            ),
        ])
    ]
