# Generated by Django 2.2.1 on 2019-11-23 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_targets', '0016_auto_20191122_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetlisttargets',
            name='priority',
            field=models.CharField(blank=True, help_text='Priority level to observe this target, as compared with the remaining                                     targets in the grouping', max_length=50),
        ),
    ]
